// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Databasechangelog = sequelize.define('databasechangelog', {
    id: {
      type: DataTypes.STRING,
    },
    author: {
      type: DataTypes.STRING,
    },
    filename: {
      type: DataTypes.STRING,
    },
    dateexecuted: {
      type: DataTypes.DATE,
    },
    orderexecuted: {
      type: DataTypes.INTEGER,
    },
    exectype: {
      type: DataTypes.STRING,
    },
    md5Sum: {
      type: DataTypes.STRING,
      field: 'md5sum',
    },
    description: {
      type: DataTypes.STRING,
    },
    comments: {
      type: DataTypes.STRING,
    },
    tag: {
      type: DataTypes.STRING,
    },
    liquibase: {
      type: DataTypes.STRING,
    },
    contexts: {
      type: DataTypes.STRING,
    },
    labels: {
      type: DataTypes.STRING,
    },
    deploymentId: {
      type: DataTypes.STRING,
      field: 'deployment_id',
    },
  }, {
    tableName: 'databasechangelog',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Databasechangelog.associate = (models) => {
  };

  return Databasechangelog;
};
